language: python
services: docker

os: linux
install: skip

arch:
  - amd64
  - arm64

python:
    - "3.6"
    - "3.7"
    - "3.8"

git:
    submodules: true

compiler:
  - clang
  - gcc


script:
    - pip install -r requirements.txt
    - python setup.py build_cmake
    - python setup.py build_ext
    - python setup.py develop
    - python tests/test_decode.py
    - python tests/test_encode.py


